<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-10-28 18:04

$extensionPath = t3lib_extMgm::extPath('enetcacheanalytics');
return array(
	'tx_enetcacheanalytics_log' => $extensionPath . 'hooks/class.tx_enetcacheanalytics_log.php',
	'tx_enetcacheanalytics_module1' => $extensionPath . 'mod1/index.php',
	'tx_enetcacheanalytics_eofe' => $extensionPath . 'hooks/class.tx_enetcacheanalytics_eofe.php',
	'tx_enetcacheanalytics_bemodule' => $extensionPath . 'interfaces/interface.tx_enetcacheanalytics_bemodule.php',
	'tx_enetcacheanalytics_bemodule_cacheanalyzer' => $extensionPath . 'classes/class.tx_enetcacheanalytics_bemodule_cacheanalyzer.php',
);
?>
